org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true

# Multi-version selector (supported: 1.21.2, 1.21.3, 1.21.4, 1.21.5)
target_mc=1.21.5
loader_version=0.18.4

mod_version=1.0.2
maven_group=dev.zymekoh.kohs
archives_base_name=kohs-offhand-whitelist
build_name_label=1.21.2 - 1.21.5
supported_minecraft_versions=1.21.2,1.21.3,1.21.4,1.21.5
